name: presen_neta
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  share_plus: ^11.0.0
  very_good_analysis: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter  

flutter: 
  uses-material-design: true
 
  assets:
    - assets/StartPage.png
    - assets/ResultPage.png
