// Mocks generated by Mockito 5.4.6 from annotations
// in presen_neta/test/features/start/presentation/page/start_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/material.dart' as _i5;
import 'package:hooks_riverpod/hooks_riverpod.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:presen_neta/shared/service/file_picker_service.dart' as _i2;
import 'package:presen_neta/shared/service/presentation_analysis_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFilePickerService_0 extends _i1.SmartFake
    implements _i2.FilePickerService {
  _FakeFilePickerService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PresentationAnalysisService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPresentationAnalysisService extends _i1.Mock
    implements _i3.PresentationAnalysisService {
  MockPresentationAnalysisService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FilePickerService get filePickerService =>
      (super.noSuchMethod(
            Invocation.getter(#filePickerService),
            returnValue: _FakeFilePickerService_0(
              this,
              Invocation.getter(#filePickerService),
            ),
          )
          as _i2.FilePickerService);

  @override
  _i4.Future<bool> analyzePdfFile(
    _i5.BuildContext? context,
    _i6.WidgetRef? ref,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#analyzePdfFile, [context, ref]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
