// Mocks generated by Mockito 5.4.6 from annotations
// in presen_neta/test/shared/service/gemini_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:google_generative_ai/google_generative_ai.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:presen_neta/shared/service/interfaces/generative_model_interface.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGenerateContentResponseInterface_0 extends _i1.SmartFake
    implements _i2.GenerateContentResponseInterface {
  _FakeGenerateContentResponseInterface_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeCountTokensResponseInterface_1 extends _i1.SmartFake
    implements _i2.CountTokensResponseInterface {
  _FakeCountTokensResponseInterface_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [GenerativeModelInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenerativeModelInterface extends _i1.Mock
    implements _i2.GenerativeModelInterface {
  MockGenerativeModelInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.GenerateContentResponseInterface> generateContent(
    List<_i4.Content>? prompt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateContent, [prompt]),
            returnValue: _i3.Future<_i2.GenerateContentResponseInterface>.value(
              _FakeGenerateContentResponseInterface_0(
                this,
                Invocation.method(#generateContent, [prompt]),
              ),
            ),
          )
          as _i3.Future<_i2.GenerateContentResponseInterface>);

  @override
  _i3.Future<_i2.CountTokensResponseInterface> countTokens(
    List<_i4.Content>? prompt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#countTokens, [prompt]),
            returnValue: _i3.Future<_i2.CountTokensResponseInterface>.value(
              _FakeCountTokensResponseInterface_1(
                this,
                Invocation.method(#countTokens, [prompt]),
              ),
            ),
          )
          as _i3.Future<_i2.CountTokensResponseInterface>);
}
