// Mocks generated by Mockito 5.4.6 from annotations
// in presen_neta/test/shared/service/presentation_analysis_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i7;

import 'package:file_picker/file_picker.dart' as _i6;
import 'package:flutter/widgets.dart' as _i2;
import 'package:flutter_riverpod/src/internals.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:presen_neta/shared/service/file_picker_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBuildContext_0 extends _i1.SmartFake implements _i2.BuildContext {
  _FakeBuildContext_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProviderSubscription_1<State> extends _i1.SmartFake
    implements _i3.ProviderSubscription<State> {
  _FakeProviderSubscription_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FilePickerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilePickerService extends _i1.Mock implements _i4.FilePickerService {
  MockFilePickerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.FilePickerResult?> pickFile() =>
      (super.noSuchMethod(
            Invocation.method(#pickFile, []),
            returnValue: _i5.Future<_i6.FilePickerResult?>.value(),
          )
          as _i5.Future<_i6.FilePickerResult?>);

  @override
  _i5.Future<String?> readFileContent(_i6.PlatformFile? file) =>
      (super.noSuchMethod(
            Invocation.method(#readFileContent, [file]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<_i7.Uint8List?> readPdfFileContent(_i6.PlatformFile? file) =>
      (super.noSuchMethod(
            Invocation.method(#readPdfFileContent, [file]),
            returnValue: _i5.Future<_i7.Uint8List?>.value(),
          )
          as _i5.Future<_i7.Uint8List?>);
}

/// A class which mocks [WidgetRef].
///
/// See the documentation for Mockito's code generation for more information.
class MockWidgetRef extends _i1.Mock implements _i3.WidgetRef {
  MockWidgetRef() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BuildContext get context =>
      (super.noSuchMethod(
            Invocation.getter(#context),
            returnValue: _FakeBuildContext_0(this, Invocation.getter(#context)),
          )
          as _i2.BuildContext);

  @override
  T watch<T>(_i3.ProviderListenable<T>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [provider]),
            returnValue: _i8.dummyValue<T>(
              this,
              Invocation.method(#watch, [provider]),
            ),
          )
          as T);

  @override
  bool exists(_i3.ProviderBase<Object?>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#exists, [provider]),
            returnValue: false,
          )
          as bool);

  @override
  void listen<T>(
    _i3.ProviderListenable<T>? provider,
    void Function(T?, T)? listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listen, [provider, listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  _i3.ProviderSubscription<T> listenManual<T>(
    _i3.ProviderListenable<T>? provider,
    void Function(T?, T)? listener, {
    void Function(Object, StackTrace)? onError,
    bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listenManual,
              [provider, listener],
              {#onError: onError, #fireImmediately: fireImmediately},
            ),
            returnValue: _FakeProviderSubscription_1<T>(
              this,
              Invocation.method(
                #listenManual,
                [provider, listener],
                {#onError: onError, #fireImmediately: fireImmediately},
              ),
            ),
          )
          as _i3.ProviderSubscription<T>);

  @override
  T read<T>(_i3.ProviderListenable<T>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#read, [provider]),
            returnValue: _i8.dummyValue<T>(
              this,
              Invocation.method(#read, [provider]),
            ),
          )
          as T);

  @override
  State refresh<State>(_i3.Refreshable<State>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#refresh, [provider]),
            returnValue: _i8.dummyValue<State>(
              this,
              Invocation.method(#refresh, [provider]),
            ),
          )
          as State);

  @override
  void invalidate(_i3.ProviderOrFamily? provider) => super.noSuchMethod(
    Invocation.method(#invalidate, [provider]),
    returnValueForMissingStub: null,
  );
}
